import type { Metadata } from "next";
import "./globals.css";
import TabbedMenu from "./TabbedMenu";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="mt-16"></div>
        {children}
        <div className="mb-16"></div>
        <TabbedMenu />
      </body>
    </html>
  );
}
